title: Introduction to Causality: A Modern Approach
description: A gentle introduction into the art and science of causal inference
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - introduction.md
  - causality.md
